name: daily-report

on:
   schedule:
     - cron: '0 10  * * 1-6' # Run every day at 10am, monday-saturday
   workflow_dispatch:
#The following is just a very basic version of running A Github Action
# jobs:
#   my-jobs:
#     runs-on: ubuntu-latest
#     steps:
#       - name: first-step
#         run: echo "hi there world!"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'
      - name: Create requirements.txt
        run: |
          echo "requests==2.31.0" > .github/workflows/requirements.txt
          echo "python-dateutil==2.8.2" >> .github/workflows/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt
      - name: Run ARCC stock check code
        env:
          API_KEY: $ {{secrets.API_KEY}}
          NEWS_API_KEY: $ {{secrets.NEWS_API_KEY}}
          APP_EMAIL_PASSWORD: $ {{secrets.APP_EMAIL_PASSWORD}}
          TO_EMAIL: $ {{secrets.TO_EMAIL}}
          MY_EMAIL: $ {{secrets.MY_EMAIL}}
        run: python .github/workflows/Stock_email_main.py
