name: daily-report

on:
   schedule:
     - cron: '0 10  * * 1-6' # Run every day at 10am, monday-saturday
   workflow_dispatch:
#The following is just a very basic version of running A Github Action
# jobs:
#   my-jobs:
#     runs-on: ubuntu-latest
#     steps:
#       - name: first-step
#         run: echo "hi there world!"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.x'
      - name: Create requirements.txt
        run: |
          echo "requests==2.31.0" > requirements.txt
          echo "twilio==8.5.0" >> requirements.txt
          echo "python-dateutil==2.8.2" >> requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run ARCC stock check code
        env:
          API_KEY: ${{secrets.API_KEY}}
          NEWS_API_KEY: ${{secrets.NEWS_API_KEY}}
          ACCOUNT_SID: ${{secrets.ACCOUNT_SID}}
          AUTH_TOKEN: ${{secrets.AUTH_TOKEN}}
          FROM_NUMBER: ${{secrets.FROM_NUMBER}}
          TO_NUMBER: ${{secrets.TO_NUMBER}}
        run: python ARCC_stock_check.py
